// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TutorBuddy_MCsoft.Data;

namespace TutorBuddy_MCsoft.Migrations
{
    [DbContext(typeof(TutorBuddy_MCsoftContext))]
    [Migration("20210812225240_newnew")]
    partial class newnew
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("TutorBuddy_MCsoft.Models.Module", b =>
                {
                    b.Property<string>("ModuleCode")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ModuleName")
                        .HasColumnType("longtext");

                    b.HasKey("ModuleCode");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("TutorBuddy_MCsoft.Models.ModulesTutored", b =>
                {
                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.Property<int>("ModuleCode")
                        .HasColumnType("int");

                    b.Property<string>("ModuleCode1")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("TutorStudentNumber")
                        .HasColumnType("int");

                    b.HasKey("StudentNumber", "ModuleCode");

                    b.HasIndex("ModuleCode1");

                    b.HasIndex("TutorStudentNumber");

                    b.ToTable("ModulesTutored");
                });

            modelBuilder.Entity("TutorBuddy_MCsoft.Models.Resource", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .HasColumnType("longtext");

                    b.Property<string>("ModuleCode")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("ModuleCode");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("TutorBuddy_MCsoft.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.Property<int?>("StudentNumber")
                        .HasColumnType("int");

                    b.Property<int?>("TutorStudentNumber")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.HasIndex("StudentNumber");

                    b.HasIndex("TutorStudentNumber");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TutorBuddy_MCsoft.Models.Session", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AmountOfPeople")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("TutorBuddy_MCsoft.Models.Student", b =>
                {
                    b.Property<int>("StudentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("LevelOfStudy")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("StudentNumber");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("TutorBuddy_MCsoft.Models.Tutor", b =>
                {
                    b.Property<int>("StudentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Approved")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("AvgRating")
                        .HasColumnType("double");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("longtext");

                    b.Property<double>("Fee")
                        .HasColumnType("double");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("StudentNumber");

                    b.ToTable("Tutors");
                });

            modelBuilder.Entity("TutorBuddy_MCsoft.Models.ModulesTutored", b =>
                {
                    b.HasOne("TutorBuddy_MCsoft.Models.Module", "Module")
                        .WithMany("ModulesTutored")
                        .HasForeignKey("ModuleCode1");

                    b.HasOne("TutorBuddy_MCsoft.Models.Tutor", "Tutor")
                        .WithMany("ModulesTutored")
                        .HasForeignKey("TutorStudentNumber");

                    b.Navigation("Module");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("TutorBuddy_MCsoft.Models.Resource", b =>
                {
                    b.HasOne("TutorBuddy_MCsoft.Models.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleCode");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("TutorBuddy_MCsoft.Models.Review", b =>
                {
                    b.HasOne("TutorBuddy_MCsoft.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentNumber");

                    b.HasOne("TutorBuddy_MCsoft.Models.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorStudentNumber");

                    b.Navigation("Student");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("TutorBuddy_MCsoft.Models.Module", b =>
                {
                    b.Navigation("ModulesTutored");
                });

            modelBuilder.Entity("TutorBuddy_MCsoft.Models.Tutor", b =>
                {
                    b.Navigation("ModulesTutored");
                });
#pragma warning restore 612, 618
        }
    }
}
